---
- hosts: sqlserver
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: adminuser
    ansible_become_password: #{kv-admin-user-password}#
  tasks:

    # - name: Install SQL Express via Choco
    #   win_chocolatey:
    #     name: sql-server-express
    #     params: /ACTION=INSTALL /FEATURES=SQLENGINE /INSTANCENAME=MSSQLSERVER /SECURITYMODE=SQL /SAPWD="P@ssword!" /SQLSVCACCOUNT="NT AUTHORITY\System" /AGTSVCACCOUNT="NT AUTHORITY\System" /SQLSYSADMINACCOUNTS="BUILTIN\Administrators" /IACCEPTSQLSERVERLICENSETERMS=1 /TCPENABLED=1 /UPDATEENABLED=False
    #     state: absent

    - name: Install SQL Man Studio
      win_chocolatey:
        name: sql-server-management-studio
        state: present
